In [1]:
import fastf1

schedule = fastf1.get_event_schedule(2024)

schedule[[
    "RoundNumber",
    "EventName",
    "Country",
    "Location"
]]

req         WARNING 	DEFAULT CACHE ENABLED! (99.09 MB) C:\Users\34620\AppData\Local\Temp\fastf1

,RoundNumber,EventName,Country,Location
0,0,Pre-Season Testing,Bahrain,Sakhir
1,1,Bahrain Grand Prix,Bahrain,Sakhir
2,2,Saudi Arabian Grand Prix,Saudi Arabia,Jeddah
3,3,Australian Grand Prix,Australia,Melbourne
4,4,Japanese Grand Prix,Japan,Suzuka
5,5,Chinese Grand Prix,China,Shanghai
6,6,Miami Grand Prix,United States,Miami
7,7,Emilia Romagna Grand Prix,Italy,Imola
8,8,Monaco Grand Prix,Monaco,Monaco
9,9,Canadian Grand Prix,Canada,Montréal
10,10,Spanish Grand Prix,Spain,Barcelona
11,11,Austrian Grand Prix,Austria,Spielberg
12,12,British Grand Prix,United Kingdom,Silverstone
13,13,Hungarian Grand Prix,Hungary,Budapest
14,14,Belgian Grand Prix,Belgium,Spa-Francorchamps
15,15,Dutch Grand Prix,Netherlands,Zandvoort
16,16,Italian Grand Prix,Italy,Monza
17,17,Azerbaijan Grand Prix,Azerbaijan,Baku
18,18,Singapore Grand Prix,Singapore,Marina Bay
19,19,United States Grand Prix,United States,Austin
20,20,Mexico City Grand Prix,Mexico,Mexico City
21,21,São Paulo Grand Prix,Brazil,São Paulo
22,22,Las Vegas Grand Prix,United States,Las Vegas
23,23,Qatar Grand Prix,Qatar,Lusail
24,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island

In [3]:
print(f"Número de eventos: {len(schedule)}")

Número de eventos: 25

In [4]:
races_2024 = schedule[
    schedule["RoundNumber"].between(1, 24)
].copy()

races_2024 = races_2024[
    ["RoundNumber", "EventName", "Country", "Location"]
].reset_index(drop=True)

races_2024

,RoundNumber,EventName,Country,Location
0,1,Bahrain Grand Prix,Bahrain,Sakhir
1,2,Saudi Arabian Grand Prix,Saudi Arabia,Jeddah
2,3,Australian Grand Prix,Australia,Melbourne
3,4,Japanese Grand Prix,Japan,Suzuka
4,5,Chinese Grand Prix,China,Shanghai
5,6,Miami Grand Prix,United States,Miami
6,7,Emilia Romagna Grand Prix,Italy,Imola
7,8,Monaco Grand Prix,Monaco,Monaco
8,9,Canadian Grand Prix,Canada,Montréal
9,10,Spanish Grand Prix,Spain,Barcelona
10,11,Austrian Grand Prix,Austria,Spielberg
11,12,British Grand Prix,United Kingdom,Silverstone
12,13,Hungarian Grand Prix,Hungary,Budapest
13,14,Belgian Grand Prix,Belgium,Spa-Francorchamps
14,15,Dutch Grand Prix,Netherlands,Zandvoort
15,16,Italian Grand Prix,Italy,Monza
16,17,Azerbaijan Grand Prix,Azerbaijan,Baku
17,18,Singapore Grand Prix,Singapore,Marina Bay
18,19,United States Grand Prix,United States,Austin
19,20,Mexico City Grand Prix,Mexico,Mexico City
20,21,São Paulo Grand Prix,Brazil,São Paulo
21,22,Las Vegas Grand Prix,United States,Las Vegas
22,23,Qatar Grand Prix,Qatar,Lusail
23,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island

In [2]:
import pandas as pd

df = pd.read_parquet("src/data/data/raw/2024/R01_Bahrain/FP1.parquet")
print(df.head())
print(df.info())
print(df.describe())

                    Time Driver DriverNumber                LapTime  \
0 0 days 00:23:29.480000    VER            1                    NaT
1 0 days 00:25:03.380000    VER            1 0 days 00:01:33.900000
2 0 days 00:27:38.741000    VER            1                    NaT
3 0 days 00:30:09.791000    VER            1                    NaT
4 0 days 00:31:43.326000    VER            1 0 days 00:01:33.535000

   LapNumber  Stint             PitOutTime              PitInTime  \
0        1.0    1.0 0 days 00:21:31.781000                    NaT
1        2.0    1.0                    NaT                    NaT
2        3.0    1.0                    NaT 0 days 00:27:36.999000
3        4.0    2.0 0 days 00:28:03.285000                    NaT
4        5.0    2.0                    NaT                    NaT

             Sector1Time            Sector2Time  ... FreshTyre  \
0                    NaT 0 days 00:00:53.688000  ...      True
1 0 days 00:00:30.147000 0 days 00:00:40.365000  ...      True
2 0 days 00:00:51.006000 0 days 00:01:05.853000  ...      True
3 0 days 00:01:03.355000 0 days 00:00:54.264000  ...     False
4 0 days 00:00:29.959000 0 days 00:00:40.204000  ...     False

              Team           LapStartTime            LapStartDate  \
0  Red Bull Racing 0 days 00:21:31.781000 2024-02-29 11:36:31.847
1  Red Bull Racing 0 days 00:23:29.480000 2024-02-29 11:38:29.546
2  Red Bull Racing 0 days 00:25:03.380000 2024-02-29 11:40:03.446
3  Red Bull Racing 0 days 00:27:38.741000 2024-02-29 11:42:38.807
4  Red Bull Racing 0 days 00:30:09.791000 2024-02-29 11:45:09.857

   TrackStatus  Position  Deleted  DeletedReason  FastF1Generated IsAccurate
0            1       NaN    False                           False      False
1            1       NaN    False                           False       True
2            1       NaN    False                           False      False
3            1       NaN    False                           False      False
4            1       NaN    False                           False       True

[5 rows x 31 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 449 entries, 0 to 448
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                449 non-null    timedelta64[ns]
 1   Driver              449 non-null    object
 2   DriverNumber        449 non-null    object
 3   LapTime             355 non-null    timedelta64[ns]
 4   LapNumber           449 non-null    float64
 5   Stint               449 non-null    float64
 6   PitOutTime          78 non-null     timedelta64[ns]
 7   PitInTime           78 non-null     timedelta64[ns]
 8   Sector1Time         388 non-null    timedelta64[ns]
 9   Sector2Time         449 non-null    timedelta64[ns]
 10  Sector3Time         449 non-null    timedelta64[ns]
 11  Sector1SessionTime  387 non-null    timedelta64[ns]
 12  Sector2SessionTime  449 non-null    timedelta64[ns]
 13  Sector3SessionTime  449 non-null    timedelta64[ns]
 14  SpeedI1             449 non-null    float64
 15  SpeedI2             449 non-null    float64
 16  SpeedFL             371 non-null    float64
 17  SpeedST             449 non-null    float64
 18  IsPersonalBest      449 non-null    bool
 19  Compound            449 non-null    object
 20  TyreLife            449 non-null    float64
 21  FreshTyre           449 non-null    bool
 22  Team                449 non-null    object
 23  LapStartTime        449 non-null    timedelta64[ns]
 24  LapStartDate        449 non-null    datetime64[ns]
 25  TrackStatus         449 non-null    object
 26  Position            0 non-null      float64
 27  Deleted             449 non-null    bool
 28  DeletedReason       449 non-null    object
 29  FastF1Generated     449 non-null    bool
 30  IsAccurate          449 non-null    bool
dtypes: bool(5), datetime64[ns](1), float64(8), object(6), timedelta64[ns](11)
memory usage: 93.5+ KB
None
                            Time                    LapTime   LapNumber  \
count                        449                        355  449.000000
mean   0 days 00:51:10.381982182  0 days 00:01:49.420408450   11.915367
min       0 days 00:16:50.925000     0 days 00:01:32.869000    1.000000
25%       0 days 00:30:55.617000     0 days 00:01:36.639000    6.000000
50%       0 days 00:53:58.821000     0 days 00:01:38.768000   12.000000
75%       0 days 01:09:30.213000     0 days 00:02:03.445500   17.000000
max       0 days 01:21:23.273000     0 days 00:02:29.934000   27.000000
std    0 days 00:20:10.064933071  0 days 00:00:17.589022216    6.785420

            Stint                 PitOutTime                  PitInTime  \
count  449.000000                         78                         78
mean     2.668151  0 days 00:40:31.522397435  0 days 00:51:22.895089743
min      1.000000     0 days 00:15:03.718000     0 days 00:17:10.290000
25%      2.000000     0 days 00:22:40.955750     0 days 00:32:54.694250
50%      3.000000     0 days 00:44:09.952000     0 days 00:51:54.716000
75%      4.000000     0 days 00:57:42.243500     0 days 01:12:57.311250
max      5.000000     0 days 01:14:47.713000     0 days 01:21:21.299000
std      1.231610  0 days 00:19:11.398106380  0 days 00:21:17.580602283

                     Sector1Time                Sector2Time  \
count                        388                        449
mean   0 days 00:00:38.188603092  0 days 00:00:48.437146993
min       0 days 00:00:29.715000     0 days 00:00:39.663000
25%       0 days 00:00:31.031250     0 days 00:00:42.094000
50%       0 days 00:00:31.677500     0 days 00:00:43.298000
75%       0 days 00:00:40.915750     0 days 00:00:54.072000
max       0 days 00:01:24.252000     0 days 00:01:17.691000
std    0 days 00:00:12.005344689  0 days 00:00:08.999936273

                     Sector3Time         Sector1SessionTime  \
count                        449                        387
mean   0 days 00:00:27.415503340  0 days 00:51:11.394457364
min       0 days 00:00:23.147000     0 days 00:17:22.813000
25%       0 days 00:00:24.143000     0 days 00:30:31.796500
50%       0 days 00:00:25.041000     0 days 00:54:15.054000
75%       0 days 00:00:29.443000     0 days 01:09:28.719000
max       0 days 00:00:46.391000     0 days 01:19:59.038000
std    0 days 00:00:04.496433651  0 days 00:19:57.811816055

              Sector2SessionTime         Sector3SessionTime     SpeedI1  \
count                        449                        449  449.000000
mean   0 days 00:50:43.002719376  0 days 00:51:10.405554565  200.142539
min       0 days 00:16:26.201000     0 days 00:16:51.068000   59.000000
25%       0 days 00:30:27.106000     0 days 00:30:55.617000  164.000000
50%       0 days 00:53:32.748000     0 days 00:53:58.821000  226.000000
75%       0 days 01:08:58.718000     0 days 01:09:30.213000  233.000000
max       0 days 01:20:55.137000     0 days 01:21:23.273000  240.000000
std    0 days 00:20:10.427647583  0 days 00:20:10.054840211   43.513824

          SpeedI2     SpeedFL     SpeedST    TyreLife  \
count  449.000000  371.000000  449.000000  449.000000
mean   222.017817  261.528302  252.440980    6.648107
min     63.000000   39.000000   54.000000    1.000000
25%    188.000000  272.000000  206.000000    3.000000
50%    242.000000  275.000000  282.000000    6.000000
75%    257.000000  279.000000  299.000000    9.000000
max    271.000000  288.000000  319.000000   20.000000
std     45.570879   50.012281   60.071064    4.106941

                    LapStartTime                   LapStartDate  Position
count                        449                            449       0.0
mean   0 days 00:48:22.330498886  2024-02-29 12:03:22.396498944       NaN
min       0 days 00:15:03.718000     2024-02-29 11:30:03.784000       NaN
25%       0 days 00:28:40.113000  2024-02-29 11:43:40.179000064       NaN
50%       0 days 00:51:26.441000  2024-02-29 12:06:26.507000064       NaN
75%       0 days 01:07:40.987000  2024-02-29 12:22:41.052999936       NaN
max       0 days 01:18:47.934000            2024-02-29 12:33:48       NaN
std    0 days 00:20:22.156252203                            NaN       NaN

In [4]:
df["Driver"].value_counts()

Driver
HUL    27
SAI    26
NOR    25
MAG    25
PIA    25
RUS    25
LEC    24
GAS    24
TSU    24
PER    24
RIC    23
HAM    22
BOT    21
VER    21
OCO    21
ALO    20
STR    20
SAR    19
ALB    17
ZHO    16
Name: count, dtype: int64