In [41]:
import fastf1

schedule = fastf1.get_event_schedule(2024)

schedule[[
    "RoundNumber",
    "EventName",
    "Country",
    "Location"
]]

,RoundNumber,EventName,Country,Location
0,0,Pre-Season Testing,Bahrain,Sakhir
1,1,Bahrain Grand Prix,Bahrain,Sakhir
2,2,Saudi Arabian Grand Prix,Saudi Arabia,Jeddah
3,3,Australian Grand Prix,Australia,Melbourne
4,4,Japanese Grand Prix,Japan,Suzuka
5,5,Chinese Grand Prix,China,Shanghai
6,6,Miami Grand Prix,United States,Miami
7,7,Emilia Romagna Grand Prix,Italy,Imola
8,8,Monaco Grand Prix,Monaco,Monaco
9,9,Canadian Grand Prix,Canada,Montréal
10,10,Spanish Grand Prix,Spain,Barcelona
11,11,Austrian Grand Prix,Austria,Spielberg
12,12,British Grand Prix,United Kingdom,Silverstone
13,13,Hungarian Grand Prix,Hungary,Budapest
14,14,Belgian Grand Prix,Belgium,Spa-Francorchamps
15,15,Dutch Grand Prix,Netherlands,Zandvoort
16,16,Italian Grand Prix,Italy,Monza
17,17,Azerbaijan Grand Prix,Azerbaijan,Baku
18,18,Singapore Grand Prix,Singapore,Marina Bay
19,19,United States Grand Prix,United States,Austin
20,20,Mexico City Grand Prix,Mexico,Mexico City
21,21,São Paulo Grand Prix,Brazil,São Paulo
22,22,Las Vegas Grand Prix,United States,Las Vegas
23,23,Qatar Grand Prix,Qatar,Lusail
24,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island

In [27]:
print(f"Número de eventos: {len(schedule)}")

Número de eventos: 25

In [28]:
races_2024 = schedule[
    schedule["RoundNumber"].between(1, 24)
].copy()

races_2024 = races_2024[
    ["RoundNumber", "EventName", "Country", "Location"]
].reset_index(drop=True)

races_2024

,RoundNumber,EventName,Country,Location
0,1,Bahrain Grand Prix,Bahrain,Sakhir
1,2,Saudi Arabian Grand Prix,Saudi Arabia,Jeddah
2,3,Australian Grand Prix,Australia,Melbourne
3,4,Japanese Grand Prix,Japan,Suzuka
4,5,Chinese Grand Prix,China,Shanghai
5,6,Miami Grand Prix,United States,Miami
6,7,Emilia Romagna Grand Prix,Italy,Imola
7,8,Monaco Grand Prix,Monaco,Monaco
8,9,Canadian Grand Prix,Canada,Montréal
9,10,Spanish Grand Prix,Spain,Barcelona
10,11,Austrian Grand Prix,Austria,Spielberg
11,12,British Grand Prix,United Kingdom,Silverstone
12,13,Hungarian Grand Prix,Hungary,Budapest
13,14,Belgian Grand Prix,Belgium,Spa-Francorchamps
14,15,Dutch Grand Prix,Netherlands,Zandvoort
15,16,Italian Grand Prix,Italy,Monza
16,17,Azerbaijan Grand Prix,Azerbaijan,Baku
17,18,Singapore Grand Prix,Singapore,Marina Bay
18,19,United States Grand Prix,United States,Austin
19,20,Mexico City Grand Prix,Mexico,Mexico City
20,21,São Paulo Grand Prix,Brazil,São Paulo
21,22,Las Vegas Grand Prix,United States,Las Vegas
22,23,Qatar Grand Prix,Qatar,Lusail
23,24,Abu Dhabi Grand Prix,United Arab Emirates,Yas Island

In [29]:
import pandas as pd

df = pd.read_parquet("src/data/data/raw/2024/Barcelona/R.parquet")
print(df.head())
print(df.info())
print(df.describe())

                    Time Driver DriverNumber                LapTime  \
0 0 days 00:58:20.507000    VER            1 0 days 00:01:23.186000
1 0 days 00:59:40.378000    VER            1 0 days 00:01:19.871000
2 0 days 01:00:59.742000    VER            1 0 days 00:01:19.364000
3 0 days 01:02:20.508000    VER            1 0 days 00:01:20.766000
4 0 days 01:03:41.335000    VER            1 0 days 00:01:20.827000

   LapNumber  Stint PitOutTime PitInTime            Sector1Time  \
0        1.0    1.0        NaT       NaT                    NaT
1        2.0    1.0        NaT       NaT 0 days 00:00:24.201000
2        3.0    1.0        NaT       NaT 0 days 00:00:23.249000
3        4.0    1.0        NaT       NaT 0 days 00:00:24.251000
4        5.0    1.0        NaT       NaT 0 days 00:00:24.165000

             Sector2Time  ... FreshTyre             Team  \
0 0 days 00:00:32.054000  ...     False  Red Bull Racing
1 0 days 00:00:31.900000  ...     False  Red Bull Racing
2 0 days 00:00:32.086000  ...     False  Red Bull Racing
3 0 days 00:00:32.339000  ...     False  Red Bull Racing
4 0 days 00:00:32.393000  ...     False  Red Bull Racing

            LapStartTime            LapStartDate  TrackStatus  Position  \
0 0 days 00:56:57.095000 2024-06-23 13:03:14.413            1       2.0
1 0 days 00:58:20.507000 2024-06-23 13:04:37.825            1       2.0
2 0 days 00:59:40.378000 2024-06-23 13:05:57.696            1       1.0
3 0 days 01:00:59.742000 2024-06-23 13:07:17.060            1       1.0
4 0 days 01:02:20.508000 2024-06-23 13:08:37.826            1       1.0

   Deleted  DeletedReason  FastF1Generated IsAccurate
0    False                           False      False
1    False                           False       True
2    False                           False       True
3    False                           False       True
4    False                           False       True

[5 rows x 31 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                1310 non-null   timedelta64[ns]
 1   Driver              1310 non-null   object
 2   DriverNumber        1310 non-null   object
 3   LapTime             1310 non-null   timedelta64[ns]
 4   LapNumber           1310 non-null   float64
 5   Stint               1310 non-null   float64
 6   PitOutTime          43 non-null     timedelta64[ns]
 7   PitInTime           42 non-null     timedelta64[ns]
 8   Sector1Time         1290 non-null   timedelta64[ns]
 9   Sector2Time         1310 non-null   timedelta64[ns]
 10  Sector3Time         1310 non-null   timedelta64[ns]
 11  Sector1SessionTime  1285 non-null   timedelta64[ns]
 12  Sector2SessionTime  1310 non-null   timedelta64[ns]
 13  Sector3SessionTime  1310 non-null   timedelta64[ns]
 14  SpeedI1             1310 non-null   float64
 15  SpeedI2             1310 non-null   float64
 16  SpeedFL             1268 non-null   float64
 17  SpeedST             1310 non-null   float64
 18  IsPersonalBest      1310 non-null   bool
 19  Compound            1310 non-null   object
 20  TyreLife            1310 non-null   float64
 21  FreshTyre           1310 non-null   bool
 22  Team                1310 non-null   object
 23  LapStartTime        1310 non-null   timedelta64[ns]
 24  LapStartDate        1310 non-null   datetime64[ns]
 25  TrackStatus         1310 non-null   object
 26  Position            1310 non-null   float64
 27  Deleted             1310 non-null   bool
 28  DeletedReason       1310 non-null   object
 29  FastF1Generated     1310 non-null   bool
 30  IsAccurate          1310 non-null   bool
dtypes: bool(5), datetime64[ns](1), float64(8), object(6), timedelta64[ns](11)
memory usage: 272.6+ KB
None
                            Time                    LapTime    LapNumber  \
count                       1310                       1310  1310.000000
mean   0 days 01:42:26.667640458  0 days 00:01:21.474285496    33.252672
min       0 days 00:58:19.889000     0 days 00:01:17.115000     1.000000
25%       0 days 01:20:24.251750     0 days 00:01:19.721250    17.000000
50%       0 days 01:42:33.346000     0 days 00:01:20.908000    33.000000
75%       0 days 02:04:40.850500     0 days 00:01:21.736250    50.000000
max       0 days 02:26:31.763000     0 days 00:01:47.447000    66.000000
std    0 days 00:25:41.313634114  0 days 00:00:03.714862411    18.917847

             Stint                 PitOutTime                  PitInTime  \
count  1310.000000                         43                         42
mean      2.208397  0 days 01:34:29.439767441  0 days 01:35:00.239928571
min       1.000000     0 days 00:57:07.090000     0 days 01:09:30.287000
25%       2.000000     0 days 01:17:42.059000     0 days 01:17:40.154750
50%       2.000000     0 days 01:34:50.136000     0 days 01:35:04.716000
75%       3.000000     0 days 01:51:31.229500     0 days 01:52:11.210500
max       4.000000     0 days 02:03:57.454000     0 days 02:03:36.017000
std       0.831075  0 days 00:18:43.633857449  0 days 00:18:00.809702938

                     Sector1Time                Sector2Time  \
count                       1290                       1310
mean   0 days 00:00:24.408948062  0 days 00:00:32.546877862
min       0 days 00:00:22.564000     0 days 00:00:31.195000
25%       0 days 00:00:23.480000     0 days 00:00:32.142000
50%       0 days 00:00:23.795000     0 days 00:00:32.529500
75%       0 days 00:00:24.059000     0 days 00:00:32.890250
max       0 days 00:00:50.157000     0 days 00:00:41.310000
std    0 days 00:00:03.488936599  0 days 00:00:00.644622377

                     Sector3Time         Sector1SessionTime  \
count                       1310                       1285
mean   0 days 00:00:24.436202290  0 days 01:42:10.254726848
min       0 days 00:00:23.246000     0 days 00:58:44.162000
25%       0 days 00:00:24.011000     0 days 01:20:39.666000
50%       0 days 00:00:24.328000     0 days 01:42:10.307000
75%       0 days 00:00:24.633500     0 days 02:04:02.172000
max       0 days 00:00:29.419000     0 days 02:25:34.328000
std    0 days 00:00:00.832799798  0 days 00:25:15.243268157

              Sector2SessionTime         Sector3SessionTime      SpeedI1  \
count                       1310                       1310  1310.000000
mean   0 days 01:42:02.298447328  0 days 01:42:26.734964885   265.604580
min       0 days 00:57:56.272000     0 days 00:58:20.136000   182.000000
25%       0 days 01:19:58.095000     0 days 01:20:24.329000   262.000000
50%       0 days 01:42:08.974500     0 days 01:42:33.402000   267.000000
75%       0 days 02:04:16.700750     0 days 02:04:40.897000   271.000000
max       0 days 02:26:07.303000     0 days 02:26:31.844000   287.000000
std    0 days 00:25:41.553923032  0 days 00:25:41.310054811     9.152605

           SpeedI2      SpeedFL      SpeedST     TyreLife  \
count  1310.000000  1268.000000  1310.000000  1310.000000
mean    270.659542   278.753943   306.511450    12.595420
min     172.000000   256.000000   243.000000     1.000000
25%     266.000000   277.000000   303.000000     7.000000
50%     271.000000   279.000000   306.000000    12.000000
75%     277.000000   281.000000   309.000000    18.000000
max     296.000000   289.000000   343.000000    37.000000
std       9.652327     3.544199    14.525164     7.407158

                    LapStartTime                   LapStartDate     Position
count                       1310                           1310  1310.000000
mean   0 days 01:41:05.189904580  2024-06-23 13:47:22.507904256    10.454962
min       0 days 00:56:57.095000     2024-06-23 13:03:14.413000     1.000000
25%       0 days 01:19:00.682000            2024-06-23 13:25:18     5.000000
50%       0 days 01:41:12.291000  2024-06-23 13:47:29.608999936    10.000000
75%       0 days 02:03:20.929750  2024-06-23 14:09:38.247749888    15.000000
max       0 days 02:25:10.637000     2024-06-23 14:31:27.955000    20.000000
std    0 days 00:25:42.391673842                            NaN     5.762345

In [30]:
df["Driver"].value_counts()

Driver
VER    66
NOR    66
HAM    66
RUS    66
LEC    66
SAI    66
PIA    66
PER    66
GAS    66
OCO    66
HUL    66
ALO    65
ZHO    65
STR    65
RIC    65
BOT    65
MAG    65
ALB    65
TSU    65
SAR    64
Name: count, dtype: int64

In [40]:
df.groupby(["Driver","LapNumber"])
df.sort_values(by=["LapNumber", "Position"], ascending=True, inplace=True)
df = df[(df["Position"] == 1.0) | (df["Position"] == 2.0)]
df[["Position", "LapNumber", "Driver", "LapTime", "LapStartTime"]].head(20)

     Position  LapNumber Driver                LapTime           LapStartTime
198       1.0        1.0    RUS 0 days 00:01:22.568000 0 days 00:56:57.095000
0         2.0        1.0    VER 0 days 00:01:23.186000 0 days 00:56:57.095000
199       1.0        2.0    RUS 0 days 00:01:19.857000 0 days 00:58:19.889000
1         2.0        2.0    VER 0 days 00:01:19.871000 0 days 00:58:20.507000
2         1.0        3.0    VER 0 days 00:01:19.364000 0 days 00:59:40.378000
200       2.0        3.0    RUS 0 days 00:01:21.103000 0 days 00:59:39.746000
3         1.0        4.0    VER 0 days 00:01:20.766000 0 days 01:00:59.742000
201       2.0        4.0    RUS 0 days 00:01:20.843000 0 days 01:01:00.849000
4         1.0        5.0    VER 0 days 00:01:20.827000 0 days 01:02:20.508000
202       2.0        5.0    RUS 0 days 00:01:20.923000 0 days 01:02:21.692000
5         1.0        6.0    VER 0 days 00:01:20.876000 0 days 01:03:41.335000
203       2.0        6.0    RUS 0 days 00:01:21.070000 0 days 01:03:42.615000
6         1.0        7.0    VER 0 days 00:01:20.973000 0 days 01:05:02.211000
204       2.0        7.0    RUS 0 days 00:01:21.306000 0 days 01:05:03.685000
7         1.0        8.0    VER 0 days 00:01:20.989000 0 days 01:06:23.184000
205       2.0        8.0    RUS 0 days 00:01:21.436000 0 days 01:06:24.991000
8         1.0        9.0    VER 0 days 00:01:21.042000 0 days 01:07:44.173000
206       2.0        9.0    RUS 0 days 00:01:21.168000 0 days 01:07:46.427000
9         1.0       10.0    VER 0 days 00:01:21.003000 0 days 01:09:05.215000
207       2.0       10.0    RUS 0 days 00:01:21.308000 0 days 01:09:07.595000